= mktrs-spring-boot-native-poc

V2024.1.0

Welcome to the Proof Of Concept project around *_Spring Boot 3.x_* which has a lot of 
improvements for the modern *_Java_* application writing.

* GraalVM
* CraC

To name a few.

The purpose here is to compile and mantain a few recipes as reference code for doing *Java/Kotlin* stuff.
The project contains two folders.

* *mktrs-spring-boot-native-java-poc:* Holds a pure Java implementation on the technologies and aspects to test.
* *mktrs-spring-boot-native-kotlin-poc:* Holds a pure Kotlin implementation on the technologies and aspects to test.

Basically what is done in the *Java* folder is replicated in the *Kotlin* folder. This way
you have a lot of reference code without distractions about a topic in testing. To follow
this goal, we have different braches to exercise some concept.

[IMPORTANT]
----
If you look into the git commit history, you will notice that the steps are sync'ed with the *_'master'_* branch
to get the *Spring Boot* version and other stuff. From now on this synchronization is done manually as 
*_'master'_* can only store one structure (be it reactive, or non reactive; the one it has now is non-reactive) 
and it would lead to merge conflicts.

Starting from _0012_ step, the programming paradigm will be only the *Reactive* paradigm.

This project will always use the latest version of *_Spring Boot_* and the current LTS JDK (as of now JDK 21).

In the future, when new steps are created, don't use neither the *master* nor the *0001-initial* branch to bootstrap
(make it your code in a brand new way). This means, for example, if you create *'0013-whatever'* it will use
the *Spring WebFlux (Reactive)* mode and the _Users_ endpoint (sample contained in either *master* or *0001-initial*)
will not go through.
----

== Branches
Each branch is named after the concept in consideration. You can browse the branch for each folder code to check
how it is built and hopefully you learn something new.

Here are the current branches.
* *master:* A basic controller using *Spring MVC* with in-memory storage. It keeps the minimal application in the series.
* *steps/0001-initial:* Used to update the minimal application concept, normally it is the same as master.
* *steps/0002-spring-mvc-redis:* From the initial app adds *Redis* support, uses *Spring MVC* (Servlet technology, blocking app model, synchronous model).
* *steps/0003-spring-webflux-redis:* From the initial app adds *Redis* support, uses *Spring WebFlux* (non-blocking app model, asynchronous model).
* *steps/0004-spring-mvc-elasticsearch:* From the initial app adds *ElasticSearch* support, uses *Spring MVC* (Servlet technology, blocking app model, synchronous model).
* *steps/0005-spring-webflux-elasticsearch:* From the initial app adds *ElasticSearch* support, uses *Spring WebFlux* (non-blocking app model, asynchronous model).
* *steps/0006-spring-mvc-mongodb:* From the initial app adds *MongoDB* support, uses *Spring MVC* (Servlet technology, blocking app model, synchronous model).
* *steps/0007-spring-webflux-mongodb:* From the initial app adds *MongoDB* support, uses *Spring WebFlux* (non-blocking app model, asynchronous model).
* *steps/0008-spring-mvc-gcp-firestore:* From the initial app adds *GCP Firestore* support, uses *Spring MVC* (Servlet technology, blocking app model, synchronous model).
* *steps/0009-spring-webflux-gcp-firestore:* From the initial app adds *GCP Firestore* support, uses *Spring WebFlux* (non-blocking app model, asynchronous model).
* *steps/0010-spring-mvc-postgresql.adoc:* From the initial app adds *PostgreSQL* support and adds *Spring Security* and *Thymeleaf* page rendering, uses *Spring MVC* (Servlet technology, blocking app model, synchronous model).
* *steps/0011-spring-webflux-postgresql.adoc:* From the initial app adds *PostgreSQL* support and adds *Spring Security* and *Thymeleaf* page rendering, uses *Spring WebFlux* (non-blocking app model, asynchronous model).
* *steps/0012-spring-webflux-oracle.adoc:* From the initial app adds *Oracle* support, uses *Spring WebFlux* (non-blocking app model, asynchronous model).

Some necessary files are to be touched as common files in all branches so from time to time those are synchronized
with all the branches.

These files are kept in the *master* branch and replicated in all other branches. Usually the versions of libraries in 
'pom.xml' (Maven) or eventually 'build.gradle' (Gradle with Groovy) or 'build.gradle.kts' (Gradle with Kotlin), this 
*README.adoc*, etc.

Each branch holds a *README* to put into place, notes, tips, etc., around the technology being used there.

* README.adoc in *master* branch.
* README-0001-initial.adoc.
* README-0002-spring-mvc-redis.adoc.
* README-0003-spring-webflux-redis.adoc.
* README-0004-spring-mvc-elasticsearch.adoc.
* README-0005-spring-webflux-elasticsearch.adoc.
* README-0006-spring-mvc-mongodb.adoc.
* README-0007-spring-webflux-mongodb.adoc.
* README-0008-spring-mvc-gcp-firestore.adoc
* README-0009-spring-webflux-gcp-firestore.adoc
* README-0010-spring-mvc-postgresql.adoc
* README-0011-spring-webflux-postgresql.adoc
* README-0012-spring-webflux-oracle.adoc

[WARNING]
====
Whenever it is required to make adjustment to the common files which need to be replicated to all branches, 
they must be added/updated in the *master* branch. If you make any changes to the code base, then run the
unit tests to validate nothing has broken. 

Common files are (present at all times in the branches):

* README files. 

Make this synchronization manually from now on.
====

== References

=== GCP (Firebase/Firestore)
* https://www.knowledgefactory.net/2023/02/google-cloud-firestore-spring-boot-spring-webflux-build-reactive-crud-rest-apis.html[Google Cloud Firestore + Spring Boot + Spring WebFlux - Build Reactive CRUD REST APIs^]
* https://firebase.google.com/docs/firestore/pricing#:~:text=Cloud%20Firestore%20offers%20free%20quota,reset%20around%20midnight%20Pacific%20time.[Understand Cloud Firestore billing^]
* https://cloud.google.com/free[Google Cloud Platform Free^]
* https://partner.cloudskillsboost.google/[Google Cloud Skills Boost for Partners^]
* https://firebase.google.com/docs/firestore/quickstart[Get started with Cloud Firestore^]

=== Kotlin
* https://www.baeldung.com/kotlin/java-8-stream-vs-kotlin[Java 8 Stream API Analogies in Kotlin^]
* https://www.tutorialspoint.com/kotlin/index.htm[Kotlin Tutorial^]
* https://medium.com/codex/kotlin-why-no-collectors-ba314c6f6b1e[Kotlin: Why no Collectors?^]

=== Spring Boot
* https://stackabuse.com/how-to-return-http-status-codes-in-a-spring-boot-application/[How to Return HTTP Status Codes in a Spring Boot Application^]

=== Spring Data
* https://www.baeldung.com/spring-data-redis-tutorial[Introduction to Spring Data Redis^]
* https://github.com/spring-projects/spring-data-examples/tree/main/redis[Spring Data Examples (Official repository)^]
* https://github.com/kasramp/spring-data-redis-example-kotlin[Spring Data Redis Example with Kotlin^]

=== Spring GCP
* https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html[Spring GCP Support]


